### ISSUE TITLE
몇가지 안되는 것들...

### ISSUE THREAD

**Issue by KOSNOWMAN** [rawady/NaverLogin-for-PHP#8]
문의합니다.
1.  "AUTO_CLOSE" => true  로 설정했는데 네이버 동의하기 단추를 클릭해도 팝업창이 사라지지 않습니다. 
   -  네이버 로그인 페이지에서 동의하지 않고 취소를 눌러도 팝업창은 사라지지 않습니다.
2.  "SHOW_LOGOUT" => true 로 설정했는데 로그인 단추 그대로 입니다
   - 동의를 선택 하면 팝업창이 사라지지 않고 팝업창내에서 로그인 성공이후의 화면이 나타납니다.
   - 팝업창을 강제로 종료하면 팝업창을 호출한 parent 페이지가 refresh 되지만, 
     로그인 처리가 안되었는지 로그인 단추가 그대로 보입니다.
3.  네이버로 로그인하기 단추 바로 옆에 echo $naver->getConnectState();로 출력시켰는데 아무런 값을 리턴하지 않습니다. 잘못 사용한건가요?

**Comment by rawady** [comment]
검토해봤는데 남겨주신 내용은 문제가 없습니다.
데모 페이지 하나 추가해서 등록해두었으니 확인부탁드립니다 ^^

**Comment by rawady** [comment]
아참, 혹시나 싶은데, 세션 사용이 가능해야 합니다~
