### ISSUE TITLE
logout 기능이 안되서 질문드립니다.

### ISSUE THREAD

**Issue by gyutae100** [rawady/NaverLogin-for-PHP#9]
[소스코드]
    function logout()
    {
        $this->refreshCount = 1;
        $data = array();
        $this->curl = curl_init();
        curl_setopt($this->curl, CURLOPT_URL, NAVER_OAUTH_URL . 'token?client_id=' . $this->client_id . '&client_secret=' . $this->client_secret . '&grant_type=delete&refresh_token=' . $this->refresh_token . '&sercive_provider=NAVER');
        curl_setopt($this->curl, CURLOPT_POST, 1);
        curl_setopt($this->curl, CURLOPT_POSTFIELDS, $data);
        curl_setopt($this->curl, CURLOPT_RETURNTRANSFER, true);
        $retVar = curl_exec($this->curl);

        //error":"invalid_request","error_description":"service_provider is missing
        echo $retVar;
        exit;

        curl_close($this->curl);
        $this->deleteSession();
        echo "<script>window.location.href = 'http://" . $_SERVER["HTTP_HOST"] . $_SERVER['PHP_SELF'] . "';</script>";
    }

에서

echo $retVar;시 error":"invalid_request","error_description":"service_provider is missing
에러가 출력됩니다. 

어떤 방식으로 작동이 가능하게 할 수 있을까요??

**Comment by natura4917** [comment]
파라미터에  sercive_provider 라고 오타가 났네요 
service_provider 로 수정하시기 바랍니다. 

--추가로 --
해당 기능은 로그아웃이 아니라 연동 해제 

>  사용자가 서비스를 더이상 이용하지 않거나 (서비스 탈퇴) 네아로의 연동을 더이상 이용하지 않을 경우 (연동 해제)

로그아웃의 경우 그냥 로그인 세션을 날려주시면 됩니다.
